# Generated by Django 3.1.4 on 2023-01-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0002_auto_20230123_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorders',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('comfirmed', 'approved')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('comfirmed', 'approved')], default='pending', max_length=10),
        ),
    ]
