# Generated by Django 3.1.4 on 2023-01-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0003_auto_20230123_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorders',
            name='sub_code',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='sub_code',
        ),
    ]
