# Generated by Django 3.1.4 on 2023-01-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0004_auto_20230125_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorders',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('comfirmed', 'comfirmed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('comfirmed', 'comfirmed')], default='pending', max_length=10),
        ),
    ]
