# Generated by Django 3.1.4 on 2023-01-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0006_historicalsales_return_historicalsales_return_details_sales_return_sales_return_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorders',
            name='id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
