# Generated by Django 3.1.4 on 2023-01-19 14:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20230119_1258'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_accounts', '0003_auto_20230119_1258'),
        ('restock', '0002_auto_20230119_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrestock',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 19, 14, 35, 29, 259596, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restock',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 19, 14, 35, 40, 401105, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Restock_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.products')),
                ('profie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_accounts.profile')),
                ('restock_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restock.restock_details')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalRestock_history',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.products')),
                ('profie', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth_accounts.profile')),
                ('restock_detail', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='restock.restock_details')),
            ],
            options={
                'verbose_name': 'historical restock_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
