# Generated by Django 3.1.4 on 2023-01-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restock', '0003_auto_20230119_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalrestock_details',
            old_name='profie',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='historicalrestock_history',
            old_name='profie',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='restock_details',
            old_name='profie',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='restock_history',
            old_name='profie',
            new_name='profile',
        ),
    ]
