# Generated by Django 3.1.4 on 2023-01-26 22:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230125_1107'),
        ('restock', '0005_damages_historicaldamages'),
    ]

    operations = [
        migrations.AddField(
            model_name='damages',
            name='sub_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sub_accounts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldamages',
            name='sub_code',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.sub_accounts'),
        ),
    ]
