# Generated by Django 3.1.4 on 2023-01-26 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230125_1107'),
        ('restock', '0006_auto_20230126_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damages',
            name='sub_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.sub_accounts'),
        ),
    ]
