# Generated by Django 4.1.6 on 2023-06-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restock', '0008_historicalrestock_history_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrestock_history',
            name='product',
        ),
        migrations.RemoveField(
            model_name='historicalrestock_history',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='historicalrestock_history',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='restock_history',
            name='product',
        ),
        migrations.RemoveField(
            model_name='restock_history',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='restock_history',
            name='quantity',
        ),
    ]
