# Generated by Django 4.1.6 on 2023-09-08 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restock', '0009_remove_historicalrestock_history_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restock_history',
            name='restock_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restock.restock_details'),
        ),
    ]
