# Generated by Django 4.1.6 on 2023-09-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restock', '0010_alter_restock_history_restock_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrestock_details',
            name='wages',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='restock_details',
            name='wages',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
