# Generated by Django 4.1.6 on 2023-09-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restock', '0012_historicalrestock_shift_restock_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrestock',
            name='total_wages',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='restock',
            name='total_wages',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
