# Generated by Django 3.1.4 on 2023-01-25 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0004_auto_20230125_1107'),
        ('accounts', '0002_auto_20230121_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_receivables',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_orders.orders'),
        ),
        migrations.AddField(
            model_name='historicalaccount_receivables',
            name='reference',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales_orders.orders'),
        ),
    ]
