# Generated by Django 4.1.5 on 2023-01-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='profile_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
