# Generated by Django 3.1.4 on 2023-01-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_accounts', '0002_historicalprofile_profile_code_profile_profile_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprofile',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical profile'},
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
